// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Muhammad Farras Fajri",
            "email": "farrasfajri@example.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/v1/register": {
            "post": {
                "description": "Endpoint untuk pendaftaran anggota baru menggunakan Google ID Token (Firebase), data diri KYC, beserta upload bukti transfer manual.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Register a new cooperative member",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Firebase ID Token dari Google Auth",
                        "name": "token_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nama Lengkap sesuai KTP",
                        "name": "full_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nomor WhatsApp Aktif",
                        "name": "phone_number",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "16 Digit Nomor Induk Kependudukan (NIK)",
                        "name": "nik",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Jenis Anggota (perorangan / pemasok_usaha)",
                        "name": "member_type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Alamat Lengkap sesuai KTP",
                        "name": "address",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nama Bank Rekening Anggota",
                        "name": "bank_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nomor Rekening Bank Anggota",
                        "name": "bank_account_number",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nomor HP Referral (Opsional)",
                        "name": "referral_number",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "File Foto KTP (.jpg/.jpeg/.png)",
                        "name": "photo_ktp_url",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "File Foto Wajah / Selfie (.jpg/.jpeg/.png)",
                        "name": "photo_selfie_url",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "File Bukti Transfer Pembayaran (.jpg/.jpeg/.png)",
                        "name": "payment_proof_url",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Register Success",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request (ValidationError / TokenError / RegistrationError)",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error (ProfileError / PaymentError)",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.APIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Data sukses (opsional)"
                },
                "error": {
                    "description": "True/False",
                    "type": "boolean"
                },
                "message": {
                    "description": "Pesan untuk user",
                    "type": "string"
                },
                "type": {
                    "description": "Jenis error (ValidationError, etc)",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Koperasi Gerai API",
	Description:      "Backend API Service untuk Aplikasi Koperasi Gerai.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
